## Lokalizace

Při výpočtu metodou konečných prvků budeme potřebovat uspořádat (lokalizovat) jednotlivé matice tuhosti prvků do celkové matice tuhosti konstrukce, tento proces nazýváme lokalizací. Způsob, který budeme používat v našich cvičeních, využívá lokalizační matici (<code>loc</code>), kde na každý řádek zapisujeme kódová čísla stupňů volnosti  elementu.

In [3]:
E = 10^6;
A = [1, 2, 3];
l = 10;
loc =  [1 2 3 4; 
        3 4 5 6; 
        5 6 7 8]

K = zeros(8,8);

for i = 1:size(loc,1)

    k = stiffnessMatrix(E,A(i),l)  % element stiffness matrix 
    K(loc(i,:),loc(i,:)) = K(loc(i,:),loc(i,:)) + k;  % global stiffness matrix
    K([1 2 3 4],[1 2 3 4])
end
K

loc =

   1   2   3   4
   3   4   5   6
   5   6   7   8

K =

   1   1   1   1   0   0   0   0
   1   1   1   1   0   0   0   0
   1   1   3   3   2   2   0   0
   1   1   3   3   2   2   0   0
   0   0   2   2   5   5   3   3
   0   0   2   2   5   5   3   3
   0   0   0   0   3   3   3   3
   0   0   0   0   3   3   3   3



## Řešení soustavy

Mějme soustavu lineárních rovnic $Ax = b$, kde

In [17]:
A = [1 2 3; -1 0 2; 1 3 1] 
b = [1 0 0]'

A =

   1   2   3
  -1   0   2
   1   3   1

b =

   1
   0
   0



Pro řešení této soustavy lze využít inverzní matici $x = A^{-1}b$. Vhodnější je ale využít operátor <code>\</code>, kterým je v Matlabu implementována Gaussova eliminace.

In [20]:
format short;
% inverse
x = inv(A)*b

% Gauss elimination
x = A\b

% check
A*x1-b

x =

   0.66667
  -0.33333
   0.33333

x =

   0.66667
  -0.33333
   0.33333

ans =

  -1.1102e-16
   0.0000e+00
  -5.5511e-17

